server:
  port: 80


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS}/${MYSQL_DATABASE:bubu}&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USERNAME}
    password: ${MySQL_PASSWORD}
  jackson:
    time-zone: GMT+8
#  mvc:
#    view:
#      suffix: .html
#      prefix: /

#mybatis:
#  mapper-locations: classpath*:mapper/*Mapper.xml

wx:
  miniapp:
    configs:
      - appid: wx7a99f62eee9729f5
        secret: 5ee63148cd107ff2245e4675e279afe9
        token: #微信小程序消息服务器配置的token
        aesKey: #微信小程序消息服务器配置的EncodingAESKey
        msgDataFormat: JSON